name: Build

on:
  workflow_dispatch:
    inputs:
      testrail_report:
        description: 'Push results to testrail (true, false)'
        required: false
        default: 'false'

env:
  TESTRAIL_REPORT: ${{ github.event.inputs.testrail_report || 'false' }}